---
services:
  database:
    build: ./database
    container_name: mysql-database
    env_file:
      - ./database/.env
    ports:
      - "3306:3306"
    networks:
      - library-network
  authentication-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "5001:5001"
    depends_on:
      - database
    networks:
      - library-network
  book-service:
    build: ./book
    container_name: book-service
    ports:
      - "5002:5002"
    depends_on:
      - database
    networks:
      - library-network
  borrow-service:
    build: ./borrow
    container_name: borrow-service
    ports:
      - "5003:5003"
    depends_on:
      - database
    networks:
      - library-network
  app-service:
    build: .
    container_name: app-service
    ports:
      - "5000:5000"
    depends_on:
      - authentication-service
      - book-service
      - borrow-service
    networks:
      - library-network
networks:
  library-network:
    driver: bridge
  